pierrec/lz4

lz4_test.go
writer.go

Currently, if you write bytes that get buffered because the window size hasn't been met, we then double-count those bytes when it is finally written.
This fixes that issue.
An alternative implementation that could leave `n` in an inaccurate state is to just do n -= len(z.data) after line 129.

Return the correct length after flushing a buffered write.

---

lz4_test.go
reader.go
writer.go

If I understand correctly, the way compression with BlockDependency=true is supposed to work is that it uses the last 64K from previous blocks as the dictionary.
This patch brings this implementation inline with that. Without the changes the reader/writer, both tests fail.

Fix compression/decompression bug when BlockDependency=true

---

lz4c/main.go

Without this fix, end mark was not written correctly.

close writer

---

block.go
lz4.go
lz4_test.go
writer.go

**tl;dr** increased compression speed for small messages 95%, for large ones ~60%, but parallelism has died.
---
I like optimizing things. For one project I'm working on we wanted to support lz4 in a network compression scenario, where we are encoding small standalone sequences in a single data stream. I wrote a couple of reference implementations; flate/gzip performed quite well initially, but lz4 didn't do so well. I set about fixing that.
The first adjustment I did was to remove the parallelism in the Writer. I expect this is the most controversial change in this PR and totally understand if you don't want to accept it as a result. But, I think it makes sense... Go's built-in gzip implementation is single threaded and in most applications where lz4 support would be embedded, threading …

Increase general compression efficiency

---

block.go
lz4_test.go

Currently, `UncompressBlock` can sometimes spend a lot of time copying matches
into the destination buffer. If `mLen` is much larger than `offset`,
which will happen when uncompressing constant or mostly-constant data,
then we can get significant speedup by using a more efficient copying
strategy. A new benchmark, `BenchmarkUncompressConstantBlock`, shows ~100x
faster decompression of a 4KB constant block with this change:
```
name                       old time/op  new time/op  delta
UncompressBlock-4           292ns ± 4%   293ns ± 4%     ~     (p=0.425 n=11+11)
UncompressConstantBlock-4  25.5µs ± 5%   0.3µs ± 4%  -98.93%  (p=0.000 n=11+11)
CompressBlock-4            19.4µs ± 5%  19.3µs ± 5%     ~     (p=0.973 n=11+10)
CompressBlockHC-4          38.2µs ± 6%  38.4µs ± 4%     ~ …
```

Improve copy efficiency in block decompression

---

lz4_test.go

I was curious about exact peformance #s (or lack of them); it seems relatively slow (~60MB/s on my Xeon, I guess I have to look at why next).

Added SetBytes to the Benchmarks to see bytes/second.

---

block.go
block_test.go
decode_amd64.go
decode_amd64.s
decode_other.go
decode_test.go

~2x faster
```
name                old time/op    new time/op     delta
UncompressPg1661-4    1.62ms ± 2%     0.61ms ± 1%    -62.14%  (p=0.000 n=10+9)
UncompressDigits-4    98.3µs ± 0%     57.2µs ± 0%    -41.76%  (p=0.000 n=10+10)
UncompressTwain-4     1.05ms ± 1%     0.39ms ± 0%    -62.61%  (p=0.000 n=10+9)
UncompressRand-4      4.16µs ± 1%     4.18µs ± 0%     +0.45%  (p=0.004 n=9+9)
name                old speed      new speed       delta
UncompressPg1661-4   367MB/s ± 2%    968MB/s ± 1%   +164.12%  (p=0.000 n=10+9)
UncompressDigits-4  1.02GB/s ± 0%   1.75GB/s ± 0%    +71.72%  (p=0.000 n=10+10)
UncompressTwain-4    371MB/s ± 1%    992MB/s ± 0%   +167.47%  (p=0.000 n=10+9)
UncompressRand-4    3.94GB/s ± 1%   3.92GB/s ± 0%     -0.45%  (p=0.006 n=9+9)
name                old alloc/op   new …
```

implement block decode in assembly

---

writer.go

when finish compress data in Flush(), we need reset z.idx = 0

bugfix for issue 41

---

bench_test.go
block.go

Make the compressor skip in-compressible data.
This is a great feature of a compressor, since it will make it much better to serve it mixed data. When serving the compressor pre-compressed or random data, it will skip it very fast.
I have made the value easy to adjust.
The benchmark functions appear broken, so I added a simple one for this.
```
benchmark                     old ns/op     new ns/op     delta
BenchmarkCompressRandom-8     83659         2641          -96.84%
benchmark                     old MB/s     new MB/s     speedup
BenchmarkCompressRandom-8     195.84       6201.83      31.67x
benchmark                     old allocs     new allocs     delta
BenchmarkCompressRandom-8     0              0              +0.00%
benchmark                     old bytes     new bytes …
```

Skip in-compressible data (32x) faster

---

block.go
errors.go

Do backwards matching into the queued literals.
This seems to gain about 1.5% of compression I will add benchmarks later.
This could potentially make up for a smaller hash tables (15, maybe even 14 bits).
I will add that as a separate PR since the window size and hash table size is kinda mixed up.

Match backwards on matches

---

bench_test.go
errors.go
reader.go
reader_test.go

Allows skipping some of the uncompressed bytes. The benchmark here shows this as being only fractionally faster than reading the data into `io.Discard`, but in my use case, skipping data I don't need more than doubles performance.
I'd love to go further and skip copying the underlying data inside UncompressBlock, but that's a challenge for another day - any may involve adding too many branches to be worthwhile.

add Seek() to Reader

---

block.go
lz4.go

Did the minimal update suggested in #58 which solved the problem (thanks @klauspost )! No new tests added at this stage. Suggestions for relevant tests (without pulling in the python library) are welcome if such exist and you think they should be added.

Fix #58, block compression incompatibility with python library

---

bench_test.go
block.go

This PR makes the hashTable argument to CompressBlock optional, as well as documenting it better. Compression speed is maintained; on amd64 with Go 1.14, benchmark results are
name               old time/op    new time/op    delta
Compress-8           3.15ms ± 1%    3.14ms ± 2%    ~     (p=0.549 n=9+10)
CompressRandom-8     2.95µs ± 1%    2.86µs ± 1%  -3.13%  (p=0.000 n=9+10)
SkipBytesPg1661-8     302µs ± 3%     299µs ± 1%    ~     (p=0.065 n=9+10)
SkipBytesDigits-8    43.5µs ± 3%    47.3µs ± 1%  +8.77%  (p=0.000 n=10+10)
SkipBytesTwain-8      197µs ± 1%     197µs ± 0%    ~     (p=0.211 n=9+10)
SkipBytesRand-8      3.09µs ± 1%    3.09µs ± 1%    ~     (p=0.735 n=9+10)
CompressPg1661-8     26.8µs ± 2%    26.9µs ± 1%    ~     (p=0.143 n=10+10)
CompressDigits-8     3.64µs ± 1%    3.59µs ± 1% …

Make the hashTable argument to CompressBlock optional

---

writer.go

Signed-off-by: Cyril Tovena <cyril.tovena@gmail.com>
Fixes #65

Reset hashtable during Writer reset to ensure deterministic output.

---

internal/xxh32/xxh32zero.go
internal/xxh32/xxh32zero_test.go

This patch speeds up XXHZero.Write by having it touch XXHZero.bufused fewer times; in particular, three writes have been replaced by only one.
Benchmark results on amd64:
name      old time/op  new time/op  delta
_XXH32-8  86.3ns ± 0%  82.3ns ± 0%  -4.60%  (p=0.000 n=7+10)

Speed up XXHZero

---

internal/lz4block/decode_amd64.s

Replaced all occurrences of `MOVQ x, z; ADDQ y, z` by `LEAQ (x)(y*1), z`. There are also a few instances of the same pattern but with SUBQ. Replacing these with LEAQ with a negative offset seems to hurt performance, at least on the i7-3770K.
Benchmark results:
```
name                old time/op    new time/op    delta
Uncompress-8          8.03ns ± 1%    7.92ns ± 1%   -1.36%  (p=0.000 n=30+39)
UncompressPg1661-8     301µs ± 1%     299µs ± 1%   -0.66%  (p=0.000 n=30+39)
UncompressDigits-8    47.8µs ± 1%    43.2µs ± 1%   -9.67%  (p=0.000 n=30+40)
UncompressTwain-8      199µs ± 1%     198µs ± 1%   -0.61%  (p=0.000 n=30+39)
UncompressRand-8      3.77µs ± 2%    3.76µs ± 2%     ~     (p=0.465 n=30+40)
name                old alloc/op   new alloc/op   delta
Uncompress-8           0.00B …
```

lz4block: Optimize amd64 assembly decoder

---

reader.go
reader_test.go

To conform to io.WriterTo, lz4.Reader.WriteTo should return the number of bytes that it has successfully written to its argument, not the number of bytes (compressed or uncompressed) that it consumed from its input.

lz4.Reader.WriteTo should return number of bytes written

---

internal/lz4block/decode_other.go

This allows the compiler to simplify some bounds checks.
Benchmark results on amd64 with -tags noasm:
```
name                old time/op    new time/op    delta
Uncompress-8           499ns ± 3%     511ns ± 2%  +2.42%  (p=0.000 n=20+20)
UncompressPg1661-8    1.13ms ± 1%    1.10ms ± 1%  -2.20%  (p=0.000 n=20+20)
UncompressDigits-8    77.4µs ± 1%    75.9µs ± 1%  -1.92%  (p=0.000 n=20+20)
UncompressTwain-8      724µs ± 1%     702µs ± 1%  -3.02%  (p=0.000 n=20+19)
UncompressRand-8      3.67µs ± 2%    3.61µs ± 2%  -1.55%  (p=0.000 n=20+20)
name                old speed      new speed      delta
UncompressPg1661-8   527MB/s ± 1%   539MB/s ± 1%  +2.25%  (p=0.000 n=20+20)
UncompressDigits-8  1.29GB/s ± 1%  1.32GB/s ± 1%  +1.96%  (p=0.000 n=20+20)
UncompressTwain-8    536MB/s ± 1%   553MB/s ± 1% …
```

lz4block: Use unsigned indexes

---

internal/lz4block/decode_amd64.s
internal/lz4block/decode_other.go
internal/lz4block/decode_test.go

amd64 and noasm disagreed about length-0 inputs and literals at the end of input. They now agree with each other and with lz4 1.9.2.

Fix and test some corner cases in the decoders

---

internal/lz4block/decode_arm.s
internal/lz4block/decode_asm.go
internal/lz4block/decode_other.go
internal/lz4block/decode_test.go

Here's an ARM (32-bit) assembler version of decodeBlock. It's nearly twice as fast as the Go version for some inputs on the Raspberry PI 4B:
name                old speed      new speed       delta
UncompressPg1661-4  73.0MB/s ± 2%  135.5MB/s ± 2%   +85.74%  (p=0.000 n=10+10)
UncompressDigits-4   162MB/s ± 2%    262MB/s ± 2%   +61.57%  (p=0.000 n=10+10)
UncompressTwain-4   72.9MB/s ± 3%  139.3MB/s ± 4%   +91.26%  (p=0.000 n=10+10)
UncompressRand-4     441MB/s ± 2%    444MB/s ± 5%      ~     (p=0.196 n=8+10)
Needless to say, it passes all unit tests in internal/lz4block and at toplevel.

ARM assembly decoder

---

internal/lz4block/decode_arm.s

On ARMv7, unaligned loads work fine, but I think Go still supports ARMv5 and I believe they would crash on that arch. I haven't been able to verify this, but it's better to be safe than sorry.
Performance doesn't suffer greatly (RPI4B):
```
name                old speed      new speed      delta
UncompressPg1661-4   136MB/s ± 2%   133MB/s ± 2%  -1.65%  (p=0.040 n=10+5)
UncompressDigits-4   262MB/s ± 2%   261MB/s ± 1%    ~     (p=0.679 n=10+5)
UncompressTwain-4    139MB/s ± 4%   136MB/s ± 3%    ~     (p=0.075 n=10+5)
UncompressRand-4     444MB/s ± 5%   451MB/s ± 0%    ~     (p=0.545 n=10+1)
```

lz4block: No unaligned loads/stores in ARM decoder

---

internal/xxh32/xxh32zero.go
internal/xxh32/xxh32zero_arm.go
internal/xxh32/xxh32zero_arm.s
internal/xxh32/xxh32zero_other.go
internal/xxh32/xxh32zero_test.go

Second take on an ARM assembly version of xxhash32 (#89), now with proper handling of unaligned access. It turns out that
* ARMv7 allows unaligned access for 4-byte loads, unless in compatibility mode,
* unaligned load-multiple is never allowed, but
* the Linux kernel [catches alignment exceptions and fixes them](https://www.kernel.org/doc/html/v5.5/arm/mem_alignment.html). It's surprisingly fast at doing so.
This code is as careful as can be, so it should even run on ARMv5, which is the minimum version Go supports. It has been tested with alignment fixup turned off, in which case the previous code crashed.
Benchmark results on Raspberry Pi 4B compared to old code (with GOARM=7):
```
name                old time/op    new time/op    delta
pkg:github.com/pierrec/lz4/v4/internal/xxh32 …
```

xxh32: ARM assembler implementation

---

bench_test.go
example_test.go
internal/lz4block/block.go
internal/lz4block/block_test.go
internal/lz4stream/frame.go
lz4.go
writer_test.go

This is the PR promised in #92: uint64-typed hash tables for block compression (except in HC mode). It introduces a new API for block compression, while marking the old one deprecated, while also fixing some issues with the benchmarks. See the commit messages for details.
Benchmark results on amd64:
```
name              old time/op    new time/op    delta
Compress-8          3.13ms ± 3%    3.00ms ± 0%    -4.10%  (p=0.000 n=21+20)
CompressRandom-8    17.9µs ± 1%     8.6µs ± 1%   -51.78%  (p=0.000 n=19+20)
CompressHC-8        10.9ms ± 1%    10.2ms ± 1%    -6.12%  (p=0.000 n=21+20)
CompressPg1661-8     685µs ± 3%     699µs ± 2%    +2.05%  (p=0.000 n=21+21)
CompressDigits-8     649µs ± 3%     645µs ± 4%      ~     (p=0.083 n=19+21)
CompressTwain-8      676µs ± 2%     681µs ± 3%      ~ …
```

Smaller hashtables + block compression API

---

internal/lz4block/decode_arm.s

I've done some more work on the ARM decoder, unrolling the match copy loop to get a few % better throughput:
name                old time/op    new time/op    delta
Uncompress-4          39.0ns ± 1%    40.1ns ± 2%  +2.82%  (p=0.000 n=19+10)
UncompressPg1661-4    3.75ms ± 1%    3.54ms ± 2%  -5.83%  (p=0.000 n=18+9)
UncompressDigits-4     246µs ± 1%     237µs ± 1%  -3.51%  (p=0.000 n=20+9)
UncompressTwain-4     2.31ms ± 3%    2.16ms ± 2%  -6.14%  (p=0.000 n=20+10)
UncompressRand-4      14.2µs ± 4%    14.3µs ± 3%    ~     (p=0.130 n=18+10)
name                old speed      new speed      delta
UncompressPg1661-4   101MB/s ± 1%   107MB/s ± 2%  +6.20%  (p=0.000 n=18+9)
UncompressDigits-4   387MB/s ± 1%   401MB/s ± 1%  +3.64%  (p=0.000 n=20+9)
UncompressTwain-4    111MB/s ± 3%   119MB/s ± 2% …

Optimize ARM decoder further

---

internal/lz4block/decode_other.go

LittleEndian.Uint16 translates to a 16-byte unaligned load on platforms that have one.
amd64 with -tags=noasm:
```
name                old speed      new speed      delta
UncompressPg1661-8   339MB/s ± 1%   339MB/s ± 1%    ~     (p=0.573 n=8+10)
UncompressDigits-8  1.23GB/s ± 1%  1.25GB/s ± 1%  +0.91%  (p=0.008 n=9+10)
UncompressTwain-8    361MB/s ± 1%   362MB/s ± 0%  +0.38%  (p=0.009 n=9+10)
UncompressRand-8    3.76GB/s ± 2%  3.75GB/s ± 2%    ~     (p=0.684 n=10+10)
```
arm64:
```
name                old speed      new speed      delta
UncompressPg1661-8  57.7MB/s ± 1%  63.3MB/s ± 1%  +9.80%  (p=0.000 n=10+10)
UncompressDigits-8   205MB/s ± 1%   210MB/s ± 3%  +2.56%  (p=0.002 n=10+10)
UncompressTwain-8   60.0MB/s ± 1%  65.9MB/s ± 1%  +9.80%  (p=0.000 n=9+10)
UncompressRand-8     754MB/s …
```

Faster uint16 loading in portable decoder

---

README.md

I think it would be better to change the default branch setting for github of this repository to v4 as well.
The travis build also seems to be broken so I removed the badge.
I will also create a PR to add CI in github actions later.

Fix doc for v4

---

internal/lz4stream/block.go

Close local variable of FrameBlockData, put buffer back to pool.

Fix leak of FrameBlockData memory pool

---

writer_legacy.go
writer_legacy_test.go

See the format description here
https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md
Legacy lz4 format is still used by Linux kernel. I was able to verify
this legacy writer functionality by creating an lz4 compressed initramfs
and booting it at 5.11.7 Linux kernel.
Issue #99

Implement legacy format writer

---

fuzz/lz4.go
internal/lz4block/block.go
internal/lz4block/block_test.go
internal/lz4block/decode_test.go

Fixes #116. Includes the fuzz test that found it. The reproducer was already in the corpus.

Fix out of bounds read in CompressBlock

---

internal/lz4block/decode_amd64.go
internal/lz4block/decode_arm.go
internal/lz4block/decode_arm.s
internal/lz4block/decode_noasm.go
internal/lz4block/decode_other.go

The Go decoder is now built unconditionally and used on arm if a dictionary is provided.
Tests pass on 386, amd64, arm, arm64 with and without noasm.

lz4block: Use Go encoder with a dictionary on arm

---

writer.go
writer_test.go

This PR fixes a bug that can damage the output when writing in concurrency mode.
In current code when calling `Write()`, the writer doesn't copy the input when the buffer is empty and remaining input data fits a block. It just calls `write()` with the reference of the input slice.
https://github.com/pierrec/lz4/blob/e14f98189f2e857c91b909d68e86c3e4e81b536d/writer.go#L92-L100
And in `write()`, if concurrency is enabled, the data is processed in a goroutine asynchronously, which means `Write()` may return before the input data is actually read.
https://github.com/pierrec/lz4/blob/e14f98189f2e857c91b909d68e86c3e4e81b536d/writer.go#L134-L144
As the goroutine only keeps a reference of the input slice, and the slice may be alerted after `Write()` has returned (such as `io.Copy()` reusing a …

Writer should copy buffer in concurrency mode

---

writer.go
writer_test.go

This is an attempt to fix https://github.com/pierrec/lz4/issues/125. I noticed corruption of the LZ4 stream happens only when concurrency is used (everything works fine without it)
When compressing, [the buffer gets sent to a go routine](https://github.com/rvrangel/lz4/blob/9c7f9a786e04857aa1253f2041d95aa52983be15/writer.go#L229-L242), but when concurrency is used, the underlying array might get modified before the execution starts. causing the output of the lz4 Writer to be corrupt. Creating a copy of the buffer before solves this issue.
I also did the same thing on the main `Write()` func because according to the [documentation of Writer](https://golang.org/pkg/io/#Writer):
> Write must not modify the slice data, even temporarily. 
The existing tests don't seem to have run into this …

fix for issue 125 - lz4 data corruption when concurrency is used
